### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by andyyuan78** [NervanaSystems/nervanagpu#7]
ubgpu@ubgpu:~/github/neon/nervanagpu$ make test
Running unit tests...
nosetests -a '!slow' ""   nervanagpu
EE
======================================================================
ERROR: Failure: ImportError (cannot import name intern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubgpu/github/neon/nervanagpu/nervanagpu/__init__.py", line 15, in <module>
    from nervanagpu import NervanaGPU, GPUTensor
  File "/home/ubgpu/github/neon/nervanagpu/nervanagpu/nervanagpu.py", line 20, in <module>
    from pytools import memoize, memoize_method
  File "/usr/local/lib/python2.7/dist-packages/pytools/__init__.py", line 5, in <module>
    from six.moves import range, zip, intern, input
ImportError: cannot import name intern

======================================================================
ERROR: Failure: ImportError (cannot import name intern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubgpu/github/neon/nervanagpu/nervanagpu/__init__.py", line 15, in <module>
    from nervanagpu import NervanaGPU, GPUTensor
  File "/home/ubgpu/github/neon/nervanagpu/nervanagpu/nervanagpu.py", line 20, in <module>
    from pytools import memoize, memoize_method
  File "/usr/local/lib/python2.7/dist-packages/pytools/__init__.py", line 5, in <module>
    from six.moves import range, zip, intern, input
ImportError: cannot import name intern

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (errors=2)
make: *** [test] Error 1

**Comment by scttl** [comment]
This looks like an incompatibility between the version of pytools and the version of six you have installed.  You can find more info at the following links:
* http://stackoverflow.com/questions/27549977/python-pycuda-linux-error
* https://bitbucket.org/gutworth/six/issue/107/import-intern-module-from-sixmoves

You should be able to get around this problem by upgrading the installed version of the six and/or pytools python packages.

**Comment by andyyuan78** [comment]
In ubuntu14.04, it doesn't works.

ubgpu@ubgpu:~/github/neon/nervanagpu$ pip show Six
---
Name: six
Version: 1.9.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
ubgpu@ubgpu:~/github/neon/nervanagpu$ pip show pycuda
---
Name: pycuda
Version: 2014.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: pytools, pytest, decorator
ubgpu@ubgpu:~/github/neon/nervanagpu$ 
ubgpu@ubgpu:~/github/neon/nervanagpu$ pip show pytools
---
Name: pytools
Version: 2014.3.5
Location: /usr/local/lib/python2.7/dist-packages
Requires: decorator, appdirs, six
ubgpu@ubgpu:~/github/neon/nervanagpu$

**Comment by scttl** [comment]
Though pip show's six 1.9.0 is installed, I'm guessing you've actually got an older version of six earlier in your python path that is actually being used and causing the error you report.  To verify this run:
```
python
import six
six.__version__
```

Chances are this will display something like 1.5.2 which doesn't have the required `intern` function override.  This is probably installed because at one point you ran `apt-get install python-six`.  You can verify where this version of six is installed via: `six.__file__`.  You can also verify your python path ordering via `import sys` followed by `sys.path`

There are a few possible ways to remedy this:

1. Update your python search path such that pip installed packages (/usr/local/lib/python2.7/dist-packages) get priority over Ubuntu's apt installed packages (/usr/lib/python2.7/dist-packages).  The simplest way to do this is to first `export PYTHONPATH=/usr/local/lib/python2.7/dist-packages:$PYTHONPATH` prior to running `make test`
2. do a virtualenv based install of nervanagpu (and its dependencies) and run things out of that.  This takes care of the appropriate path mangling to ensure your dependencies will be searched for starting with your virtualenv specified dir.
3. Remove the old version of six via `sudo apt-get remove python-six`.  This isn't recommended as this version may be needed by other packages.

**Comment by andyyuan78** [comment]
cool. it works!

**Comment by pgera** [comment]
In addition to all the points mentioned above, you could also have a /usr/local/lib/python2.7/dist-packages/easy-install.pth file which messes with paths and renders PYTHONPATH useless. It adds /usr/lib/python2.7/dist-packages to the system path early on. While pip is preferred over easy-install, certain projects' makefiles might implicitly call easy-install and create the file.
